global:
  # Global configurations...

route:
  receiver: 'default-receiver'
  routes:
    - match:
        alertname: 'Watchdog'
      receiver: 'watchdog'
    - match:
        severity: 'critical'
      receiver: 'pushover'
    - match:
        severity: 'warning'
      receiver: 'pushover'

receivers:
  - name: 'default-receiver'
    # Dummy receiver
  - name: 'pushover'
    pushover_configs:
      - token: 'app_token_here'
        user_key: 'user_key_here'

  - name: 'watchdog'
    webhook_configs:
      - url: 'https://rpc.rotko.net/watchdog'
        http_config:
          authorization:
            type: Bearer
            credentials: '4ad3ef73-2f55-4817-9fbe-056f95a54f7a'
